export const BANK_CODES = [
    '', /// Selective choice on VNP page
    'VIETCOMBANK', 'VIETINBANK', 'BIDV', 'AGRIBANK',
    'SACOMBANK', 'TECHCOMBANK', 'MBBANK', 'ACB',
    'VPBANK',  'SHB', 'TPBANK', 'NCB',
     'MSBANK', 'HDBANK', 'NAMABANK',
    'VISA', 'MASTERCARD',
    'VNPAYEWALLET', 'IVB', 'CAKEPAY', 'ZALOPAY', 'SEABANK', 'ABBANK', 'VIETABANK',
    //  'MBAPP',  'VIVIET',
    // 'BIDC', 'LAOVIETBANK', 'BACABANK', 'VIB',
    // 'VNPTPAY', 'VIMASS', 'VINID', 'VIETBANK',
    // 'VIETCAPITALBANK', 'FOXPAY', 'YOLO', 'SAIGONBANK',
    // 'PVCOMBANK', 'WOORIBANK', 'UPI', 'AMEX',
    // 'KIENLONGBANK', 'LIENVIETBANK', 'BAOVIETBANK', 'PGBANK',
    // 'GPBANK', 'UOB', 'VRB', 'VIDBANK',
    // 'SHINHANBANK', 'VIETCREDIT', 'COOPBANK', 'VBSP',
    // 'MAFC', 'PAYME', 'VITING', 'PAYOO',
    // 'VIETTELPAY', 'VTCPAY', 'VCBNEO', 'TIMOBVB'
] as const