export const BANK_CODES = [
    '', /// Selective choice on VNP page
    'VIETCOMBANK', 'VIETINBANK', 'BIDV', 'AGRIBANK',
    'SACOMBANK', 'TECHCOMBANK', 'MBBANK', 'ACB',
    'VPBANK', 'DONGABANK', 'SHB', 'EXIMBANKOMNI',
    'HSBC', 'EXIMBANK', 'TPBANK', 'NCB',
    'OJB', 'MSBANK', 'HDBANK', 'NAMABANK',
    'OCB', 'VISA', 'VNMART', 'MASTERCARD',
    'VNPAYEWALLET', 'JCB', 'SCB', 'IVB',
    'ABBANK', 'CAKEPAY', 'VCBPAY', 'SEABANK',
    'VIETABANK', 'MBAPP', 'ZALOPAY', 'VIVIET',
    'BIDC', 'LAOVIETBANK', 'BACABANK', 'VIB',
    'VNPTPAY', 'VIMASS', 'VINID', 'VIETBANK',
    'VIETCAPITALBANK', 'FOXPAY', 'YOLO', 'SAIGONBANK',
    'PVCOMBANK', 'WOORIBANK', 'UPI', 'AMEX',
    'KIENLONGBANK', 'LIENVIETBANK', 'BAOVIETBANK', 'PGBANK',
    'GPBANK', 'UOB', 'VRB', 'VIDBANK',
    'SHINHANBANK', 'VIETCREDIT', 'COOPBANK', 'VBSP',
    'MAFC', 'PAYME', 'VITING', 'PAYOO',
    'VIETTELPAY', 'VTCPAY', 'VCBNEO', 'TIMOBVB'
] as const