import BlogNavMenu from "@/components/blog/BlogNavMenu";
import { InitBlogStore } from "@/components/store_cleaners/InitBlogStore";
import { InitGenreStore } from "@/components/store_cleaners/ResetBlogStore";
import { Locale, routing } from "@/i18n/routing";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Roboto } from "next/font/google";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }


  

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${roboto.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <header className="shadow-md">
            <div className="main-container">
              <InitGenreStore />
              <InitBlogStore />
              <BlogNavMenu />
            </div>
          </header>
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
